// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztuqdyxjzyeszmvoiahq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dXFkeXhqenllc3ptdm9pYWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzI1NDIsImV4cCI6MjA2NTA0ODU0Mn0.y4bFnSidOX3sM5_IwUdgXXQgK2MKBEcraQ3iIfdfBvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);